routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\VentaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('productos', ProductoController::class);
Route::resource('categorias', CategoriaController::class);
Route::resource('vender', VentaController::class);

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Producto extends Model
{
    use HasFactory;

    public function categoria()
    {
        return $this->belongsTo(Categoria::class, 'id_categoria');
    }

    public static function mayorStock()
    {
        $producto = DB::select('SELECT * 
                                FROM productos
                                ORDER BY stock DESC
                                LIMIT 1');
        return $producto[0];
    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Producto;
use App\Http\Requests\StoreProductoRequest;
use App\Http\Requests\UpdateProductoRequest;
use App\Models\Categoria;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productos = Producto::with('categoria')->get();
        return view('productos.index', compact('productos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::all();
        return view('productos.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductoRequest $request)
    {
        $producto = new Producto();
        $producto->nombre = $request->nombre;
        $producto->referencia = $request->referencia;
        $producto->precio = $request->precio;
        $producto->peso = $request->peso;
        $producto->stock = $request->stock;
        $producto->id_categoria = $request->id_categoria;
        if ($producto->save()) {
            return redirect()->route('productos.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue guardado correctamente']);
        } else {
            return redirect()->route('productos.index')->with(['type' => 'danger', 'message' => 'Error, el registro fue guardado incorrectamente']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function show(Producto $producto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = Producto::find($id);
        $categorias = Categoria::all();
        return view('productos.edit', compact('categorias', 'producto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateProductoRequest  $request
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductoRequest $request, $id)
    {
        $producto = Producto::find($id);
        $producto->nombre = $request->nombre;
        $producto->referencia = $request->referencia;
        $producto->precio = $request->precio;
        $producto->peso = $request->peso;
        $producto->stock = $request->stock;
        $producto->id_categoria = $request->id_categoria;


        if ($producto->save()) {
            return redirect()->route('productos.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue actualizado correctamente']);
        } else {
            return redirect()->route('productos.index')->with(['type' => 'danger', 'message' => 'Error al actualizar registro']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $producto = Producto::find($id);
        if ($producto->delete()) {
            return redirect()->route('productos.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue eliminado correctamente']);
        } else {
            return redirect()->route('productos.index')->with(['type' => 'danger', 'message' => 'Error al eliminar registro']);
        }
    }   
}

resources/views/productos/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Productos')



@section('content')
<div class="card card-primary mt-4">
    <div class="card-header">
        <h3 class="card-title">Registrar Producto</h3>
    </div>
    <form action="{{ route('productos.store') }}" method="POST">
        @csrf
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="form-group">
                <label for="nombre">Nombre del producto</label>
                <input required type="text" name="nombre" class="form-control" id="nombre" placeholder="Ingrese el nombre del producto" 
                value="{{ old('nombre') }}">
            </div>
            <div class="form-group">
                <label for="referencia">Referencia</label>
                <input required type="text" name="referencia" class="form-control" id="referencia" placeholder="Referencia"
                value="{{ old('referencia') }}">
            </div>
            <div class="form-group">
                <label for="precio">Precio</label>
                <input required type="number" name="precio" class="form-control" id="precio" placeholder="Precio"
                value="{{ old('precio') }}">
            </div>
            <div class="form-group">
                <label for="peso">Peso</label>
                <input required type="number" name="peso" class="form-control" id="peso" placeholder="Peso"
                value="{{ old('peso') }}">
            </div>
            <div class="form-group">
                <label for="stock">Stock</label>
                <input required type="number" name="stock" class="form-control" id="peso" placeholder="Stock"
                value="{{ old('stock') }}">
            </div>
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select required name="id_categoria" class="form-control" id="id_categoria" value="{{ old('id_categoria') }}">
                    <option value="">--Selecione la categoria--</option>
                    @foreach ($categorias as $categoria)
                    <option value="{{$categoria->id}}">{{$categoria->nombre}}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Gurdar</button>
        </div>
    </form>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/productos/delete.blade.php
<div class="modal" tabindex="-1" role="dialog" id="product-{{$producto->id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Eliminar producto "{{$producto->nombre}}"</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el producto?</p>
            </div>
            <div class="modal-footer">
                <form action="{{route('productos.destroy', $producto->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Si</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/productos/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Productos')


@section('content')
<div class="card card-primary mt-4">
    <div class="card-header">
        <h3 class="card-title">Editar Producto</h3>
    </div>
    <form action="{{ route('productos.update', $producto->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="form-group">
                <label for="nombre">Nombre del producto</label>
                <input required type="text" name="nombre" class="form-control" id="nombre" placeholder="Ingrese el nombre del producto" 
                value="{{ old('nombre', $producto->nombre) }}">
            </div>
            <div class="form-group">
                <label for="referencia">Referencia</label>
                <input required type="text" name="referencia" class="form-control" id="referencia" placeholder="Referencia"
                value="{{ old('referencia', $producto->referencia) }}">
            </div>
            <div class="form-group">
                <label for="precio">Precio</label>
                <input required type="number" name="precio" class="form-control" id="precio" placeholder="Precio"
                value="{{ old('precio', $producto->precio) }}">
            </div>
            <div class="form-group">
                <label for="peso">Peso</label>
                <input required type="number" name="peso" class="form-control" id="peso" placeholder="Peso"
                value="{{ old('peso', $producto->peso) }}">
            </div>
            <div class="form-group">
                <label for="stock">Stock</label>
                <input required type="number" name="stock" class="form-control" id="peso" placeholder="Stock"
                value="{{ old('stock', $producto->stock) }}">
            </div>
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select required name="id_categoria" class="form-control" id="id_categoria" value="{{ old('id_categoria', $producto->id_categoria) }}">
                    <option value="">--Selecione la categoria--</option>
                    @foreach ($categorias as $categoria)
                    <option value="{{$categoria->id}}" {{$producto->id_categoria == $categoria->id ? 'selected': ''}}>{{$categoria->nombre}}</option>
                    @endforeach
                </select>
            </div>


        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
    </form>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/productos/index.blade.php
@extends('adminlte::page')

@section('title', 'Productos')

@section('content_header')
<h1>Productos</h1>
@stop

@section('content')
@if (Session::has('message'))
<div class="alert alert-{{Session::get('type')}}">
    {{Session::get('message')}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <a href="/productos/create" class="btn btn-primary">Crear Producto</a>
                </h3>

            </div>

            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre de producto</th>
                            <th>Referencia</th>
                            <th>Precio</th>
                            <th>Peso</th>
                            <th>Stock</th>
                            <th>Categoría</th>
                            <th>Fecha de creación</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($productos as $producto)
                        <tr>
                            <td>{{$producto->id}}</td>
                            <td>{{$producto->nombre}}</td>
                            <td>{{$producto->referencia}}</td>
                            <td>{{$producto->precio}}</td>
                            <td>{{$producto->peso}}</td>
                            <td>{{$producto->stock}}</td>
                            <td>{{isset($producto->categoria->nombre) ? $producto->categoria->nombre : ''}}</td>
                            <td>{{ date_format($producto->created_at, 'd-m-Y') }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a href="{{ route('productos.edit', $producto) }}" class="btn btn-primary">Editar</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#product-{{$producto->id}}">Eliminar</button>
                                </div>
                            </td>
                        </tr>
                        @include('productos.delete')
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop