routes/web.php
<?php

use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\VentaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('productos', ProductoController::class);
Route::resource('categorias', CategoriaController::class);
Route::resource('vender', VentaController::class);

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    use HasFactory;
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categoria;
use App\Http\Requests\StoreCategoriaRequest;
use App\Http\Requests\UpdateCategoriaRequest;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::all();       
        return view('categorias.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categorias.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCategoriaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoriaRequest $request)
    {
        $categoria = new Categoria();
        $categoria->nombre = $request->nombre;       
        if ($categoria->save()) {
            return redirect()->route('categorias.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue guardado correctamente']);
        } else {
            return redirect()->route('categorias.index')->with(['type' => 'danger', 'message' => 'Error, el registro fue guardado incorrectamente']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function show(Categoria $categoria)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = Categoria::find($id);
        return view('categorias.edit', compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateCategoriaRequest  $request
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriaRequest $request, $id)
    {
        $categoria = Categoria::find($id);
        $categoria->nombre = $request->nombre;       
        if ($categoria->save()) {
            return redirect()->route('categorias.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue actualizado correctamente']);
        } else {
            return redirect()->route('categorias.index')->with(['type' => 'danger', 'message' => 'Error al actualizar registro']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Categoria  $categoria
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categoria = Categoria::find($id);
        if ($categoria->delete()) {
            return redirect()->route('categorias.index')->with(['type' => 'info', 'message' => 'Exito, el registro fue eliminado correctamente']);
        } else {
            return redirect()->route('categorias.index')->with(['type' => 'danger', 'message' => 'Error al eliminar registro']);
        }
    }
}

resources/views/categorias/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Categoria')

@section('content')
<div class="card card-primary mt-4">
    <div class="card-header">
        <h3 class="card-title">Registrar Categoria</h3>
    </div>
    <form action="{{ route('categorias.store') }}" method="POST">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="nombre">Nombre categoria</label>
                <input required type="text" name="nombre" class="form-control" id="nombre" placeholder="Ingrese el nombre de la categoria">
            </div>     
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/categorias/delete.blade.php
<div class="modal" tabindex="-1" role="dialog" id="categoria-{{$categoria->id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Eliminar categoria "{{$categoria->nombre}}"</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar la categoria?</p>
            </div>
            <div class="modal-footer">
                <form action="{{route('categorias.destroy', $categoria->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Si</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/categorias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Categoria')

@section('content')
<div class="card card-primary mt-4">
    <div class="card-header">
        <h3 class="card-title">Editar Categoria</h3>
    </div>
    <form action="{{ route('categorias.update', $categoria->id) }}" method="POST">
        @csrf
        @method('PUT')
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="nombre">Nombre categoria</label>
                <input required type="text" name="nombre" class="form-control" id="nombre" placeholder="Ingrese el nombre de la categoria" value="{{$categoria->nombre}}">
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
    </form>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/categorias/index.blade.php
@extends('adminlte::page')

@section('title', 'Categorias')

@section('content_header')
<h1>Categorias</h1>
@stop

@section('content')
@if (Session::has('message'))
<div class="alert alert-{{Session::get('type')}}">
    {{Session::get('message')}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    <a href="/categorias/create" class="btn btn-primary">Crear categoria</a>
                </h3>

            </div>

            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre de categoria</th>
                            <th>Fecha de creación</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($categorias as $categoria)
                        <tr>
                            <td>{{$categoria->id}}</td>
                            <td>{{$categoria->nombre}}</td>
                            <td>{{ date_format($categoria->created_at, 'd-m-Y')}}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a href="{{ route('categorias.edit', $categoria) }}" class="btn btn-primary">Editar</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#categoria-{{$categoria->id}}">Eliminar</button>
                                </div>
                            </td>
                        </tr>
                        @include('categorias.delete')
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop